# Generated by Django 4.2.2 on 2024-05-01 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userform',
            name='DOB',
        ),
        migrations.AddField(
            model_name='userform',
            name='city',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='userform',
            name='email',
            field=models.EmailField(default=' ', max_length=254),
        ),
        migrations.AddField(
            model_name='userform',
            name='password',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='userform',
            name='phone_no',
            field=models.CharField(default=' ', max_length=10),
        ),
        migrations.AddField(
            model_name='userform',
            name='username',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='userform',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
