# Generated by Django 4.2.2 on 2024-04-16 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_rename_dob_userform_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='userform',
            name='city',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='userform',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='userform',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='userform',
            name='password',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='userform',
            name='phone_no',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='userform',
            name='dob',
            field=models.DateField(default=None),
        ),
    ]
