# Generated by Django 4.2.2 on 2024-04-24 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_userform_city_userform_email_userform_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userform',
            old_name='email',
            new_name='username',
        ),
    ]
