# Generated by Django 4.2.2 on 2024-04-25 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_rename_email_userform_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userform',
            old_name='username',
            new_name='email',
        ),
    ]
